// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKCaLcZJTWu1kXePScQ5U0McP3HjE_DA4',
    appId: '1:940996181052:android:17f5e223f6e1520a0ed739',
    messagingSenderId: '940996181052',
    projectId: 'senslinq-8c1d1',
    storageBucket: 'senslinq-8c1d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4acdpGjDr07lKvipQNtUTwzqRZPJgli4',
    appId: '1:940996181052:ios:aa6e3b3a7b4537970ed739',
    messagingSenderId: '940996181052',
    projectId: 'senslinq-8c1d1',
    storageBucket: 'senslinq-8c1d1.appspot.com',
    iosBundleId: 'com.example.senslinq',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhqn3CSzBZqP6Fanbd23ly7ew2kgT8UtM',
    appId: '1:940996181052:web:0e022a15c08b185d0ed739',
    messagingSenderId: '940996181052',
    projectId: 'senslinq-8c1d1',
    authDomain: 'senslinq-8c1d1.firebaseapp.com',
    storageBucket: 'senslinq-8c1d1.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4acdpGjDr07lKvipQNtUTwzqRZPJgli4',
    appId: '1:940996181052:ios:aa6e3b3a7b4537970ed739',
    messagingSenderId: '940996181052',
    projectId: 'senslinq-8c1d1',
    storageBucket: 'senslinq-8c1d1.appspot.com',
    iosBundleId: 'com.example.senslinq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhqn3CSzBZqP6Fanbd23ly7ew2kgT8UtM',
    appId: '1:940996181052:web:0c7a9fb02403a7040ed739',
    messagingSenderId: '940996181052',
    projectId: 'senslinq-8c1d1',
    authDomain: 'senslinq-8c1d1.firebaseapp.com',
    storageBucket: 'senslinq-8c1d1.appspot.com',
  );

}